#pragma once

enum RandomizationOptions {
	RANDOMIZE_INTRO_POKEMON,
	RANDOMIZE_STARTER_POKEMON,
	RANDOMIZE_EVOLUTIONS,
	RANDOMIZE_WILD_POKEMON,
	RANDOMIZE_TRAINERS,
	RANDOMIZE_GIFT_POKEMON,
	RANDOMIZE_STATIC_POKEMON,
	RANDOMIZE_GAME_CORNER_POKEMON,
	RANDOMIZE_STATIC_ITEMS,
	ENABLE_SHINY_MODE,
	RANDOMIZE_POKEMON_PALLETES,
};
